### ISSUE TITLE
colorscheme lost  while use with `import type...` keyword in typescript

### ISSUE THREAD

**Issue by zennolux** [sainnhe/everforest#135]
just use `import ...`

![image](https://github.com/sainnhe/everforest/assets/147602513/6a06750a-0aaa-48af-b87e-969b8592a67b)

but  while using  `import type ...`

![image](https://github.com/sainnhe/everforest/assets/147602513/f4eaa0c7-ad6f-4be5-8097-7fd72d5d7f2a)

all colors become the same after the keyword `type`

**Comment by antoineco** [comment]
This is a Vim syntax issue. 
What Vim version are you using? Are you using a specific syntax plugin for TypeScript?

**Comment by zennolux** [comment]
NVIM v0.10.0  

I only used Tree-Sitter for TypeScript and did not use any other special extra plugins.

**Comment by zennolux** [comment]
Quite strange, this issue still exists even if I remove the whole configuration `~/.config/neovim`

```bash
mv ~/.config/nvim ~/.config/nvim.bak
```

![image](https://github.com/sainnhe/everforest/assets/147602513/8c4327e5-6518-4e72-81e4-1a29d8b7d13a)

**Comment by antoineco** [comment]
I'm not surprised that you are seeing the same result without plugin.
Based on your screenshot, you are not using Tree-sitter for TypeScript files, but instead the native Vim syntax mechanism (it says "Syntax" instead of "Treesitter" on the first line). The built-in Vim syntax for TypeScript is probably outdated and/or inaccurate.

You can install the Tree-sitter syntax with:
```vim
:TSInstall typescript
```

**Comment by antoineco** [comment]
I'm closing the issue because it isn't related to Everforest specifically, but feel free to continue the conversation in case you need more information about enabling Tree-sitter highlighting.

**Comment by zennolux** [comment]
Thank you for your patient answer!
