### ISSUE TITLE
Emacs support

### ISSUE THREAD

**Issue by Barbaross93** [sainnhe/everforest#35]
### Description

This is probably a long shot, but would it be possible to create an emacs version of this color scheme?

**Comment by jef** [comment]
Definitely! I don't know how emacs is structured, but perhaps someone will create it. It's a possibility nonetheless!

Take a look at https://github.com/sainnhe/forest-night/wiki. You'll find ports and we'll continue to add ports as this list grows!

**Comment by sainnhe** [comment]
Porting this color scheme to other apps is not hard IMO, all you need to do is simply replacing the color code in the corresponding gruvbox color scheme and adjust some UI colors, I finished these jobs in a single [commit](https://github.com/sainnhe/forest-night/commit/52db1e386fcf6bf62c648cce879bf593c3feaf52) based on [gruvbox-material](https://github.com/sainnhe/gruvbox-material). So you can consider porting this color scheme based on [greduan/emacs-theme-gruvbox](https://github.com/greduan/emacs-theme-gruvbox).

Since I and @jef don't use emacs, it might be better to be ported and maintained by emacs users. You can try to port it by yourself, or consider posting on emacs communities (e.g. [r/emacs](http://reddit.com/r/emacs)) to seek help.

**Comment by Theory-of-Everything** [comment]
If there is still interest in this topic, I recently started porting everforest hard dark to emacs.
Its far from being complete at the current state, but it is still very usable.

repo if this peaks interest: https://sr.ht/~theorytoe/everforest-hard-dark-theme/

**Comment by Theory-of-Everything** [comment]
As a bit of an update, my emacs port is pretty usable at this point.
I have implemented both hard-dark and hard-light, with medium and soft on the way.
If you wish to close this issue and link the project in the wiki, go ahead as it is nearly complete.

Repos:
- https://github.com/Theory-of-Everything/everforest-theme
- https://git.sr.ht/~theorytoe/everforest-theme

**Comment by sainnhe** [comment]
Great work!

**Comment by Prayag2** [comment]
> As a bit of an update, my emacs port is pretty usable at this point. I have implemented both hard-dark and hard-light, with medium and soft on the way. If you wish to close this issue, go ahead.
> 
> Repos:
> 
>     * https://github.com/Theory-of-Everything/everforest-theme
> 
>     * https://git.sr.ht/~theorytoe/everforest-theme

Hey, just wanted to let you know that ~git.sr.ht~ isn't working and the GitHub repository is readonly so I'm unable to open an issue that I've been facing with the theme. Do you mind making the GitHub repository the actual repository?

**Comment by Theory-of-Everything** [comment]
I have re-opened the issues
I have stopped using sourcehut for a multitude of reasons, so the github should be the canonical repo for now
