### ISSUE TITLE
Cursorline and statusline backgrounds indistinguishable in split windows

### ISSUE THREAD

**Issue by rameshsanth** [sainnhe/everforest#49]
The background color for the statusline and the cursorline are the same..
When you have split windows, there are 2 lines per window with same background. This becomes very confusing as soon as you have 3 split windows.. It'd be nicer to have the cursorline appear different from the statusline.

See the attached screenshot 

![Screen Shot 2021-07-16 at 3 16 18 PM](https://user-images.githubusercontent.com/22250291/126013700-ef4c9131-f958-4815-ade8-e71dce183963.png)

**Comment by antoineco** [comment]
@rameshsanth this looks more like a problem of interoperability than a problem with the color scheme itself.

What color would you suggest instead of the current behavior?

**Comment by antoineco** [comment]
I'm going to go ahead and close this issue because it is old and inactive, but as a final word please note that it is a well accepted convention for color schemes to use the same background color for `CursorLine`
/`CursorColumn` and `StatusLine`. I'm not saying it is necessarily a good practice, but here are some examples of this convention among very popular Vim color schemes:

<details>
<summary>
<h4>:art: Gruvbox</h4>
</summary>
<img width="626" alt="gruvbox" src="https://user-images.githubusercontent.com/3299086/187379550-b8d8e9b2-86be-4614-8142-d54a772b66eb.png">
</details>

<details>
<summary>
<h4>:art: Nord</h4>
</summary>
<img width="661" alt="nord" src="https://user-images.githubusercontent.com/3299086/187379562-51155f41-e75c-4330-aaf4-96fe1f9bdbcf.png">
</details>

<details>
<summary>
<h4>:art: Dracula</h4>
</summary>
<img width="625" alt="dracula" src="https://user-images.githubusercontent.com/3299086/187383659-385b65ac-8a3a-45aa-8705-e2cc31d31fcf.png">
</details>

---

My personal recommendation is to use a syntax highlight override inside your vimrc and adjust the cursorline color to something that matches your preferences.

In the example below, I'm setting it to Everforest's [`bg_green` color](https://github.com/sainnhe/everforest/blob/225e0c40499d5bc7a49c25a3c3a33a10e6a23e1a/autoload/everforest.vim#L73) (which doesn't clash with `CursorLine` but clashes with `DiffAdd` so it wouldn't be a good default either):

<details>
<summary>
<h4>:page_facing_up: .vimrc (Vim)</h4>
</summary>

```vim
" .vimrc

" Apply custom highlights on colorscheme change.
" Must be declared before executing ':colorscheme'.
augroup custom_highlights_everforest
  autocmd!
  " cursorline
  autocmd ColorScheme everforest 
  \       hi CursorLine   guibg=#445349 |
  \       hi CursorColumn guibg=#445349
augroup END

colorscheme everforest
```

</details>

<details>
<summary>
<h4>:page_facing_up: init.lua (Neovim)</h4>
</summary>

```lua
-- init.lua (Neovim)

-- Apply custom highlights on colorscheme change.
-- Must be declared before executing ':colorscheme'.
grpid = vim.api.nvim_create_augroup('custom_highlights_everforest', {})
vim.api.nvim_create_autocmd('ColorScheme', {
  group = grpid,
  pattern = 'everforest',
  command = -- cursorline
            'hi CursorLine   guibg=#445349 |' ..
            'hi CursorColumn guibg=#445349'
})

vim.cmd'colorscheme everforest'
```

</details>

Result:

<img width="624" alt="result" src="https://user-images.githubusercontent.com/3299086/187392091-556cd114-ea1b-4df6-b853-7cdf4f27da8d.png">
