### ISSUE TITLE
Lspsaga: highlighting glitches with diagnostics popups

### ISSUE THREAD

**Issue by fans3210** [sainnhe/everforest#87]
### I have done the following steps before reporting this issue:

- [X] I have searched the existing issues
- [X] I have read the FAQ in the help doc

### Operating system/version

macOS Monterey

### Terminal emulator/version

Alacritty 

### $TERM environment variable

screen-256color

### Tmux version

tmux 3.2a

### Feature matrix

```
defx: health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

null-ls: require("null-ls.health").check()
========================================================================
  - OK: prettierd: the command "prettierd" is executable.
  - OK: black: the command "black" is executable.
  - OK: eslint_d: the command "eslint_d" is executable.
  - OK: golangci_lint: the command "golangci-lint" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='tmux'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: screen-256color

nvim-lsp-installer: require("nvim-lsp-installer.health").check()
========================================================================
## nvim-lsp-installer report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.3 darwin/amd64`
  - WARNING: **cargo**: not available
  - OK: **luarocks**: `/usr/local/bin/luarocks 3.7.0`
  - OK: **Ruby**: `ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]`
  - OK: **RubyGem**: `3.0.3.1`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.6.0`
  - OK: **node**: `v18.0.0`
  - OK: **python3**: `Python 3.9.10`
  - OK: **pip3**: `pip 21.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
  - OK: **javac**: `javac 11.0.8`
  - OK: **java**: `openjdk version "11.0.8" 2020-07-14`
  - WARNING: **julia**: not available
  - ERROR: **wget**: not available
  - OK: **curl**: `curl 7.79.1 (x86_64-apple-darwin21.0) libcurl/7.79.1 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.45.1`
  - OK: **gzip**: `Apple gzip 353.100.22`
  - OK: **tar**: `bsdtar 3.5.1 - libarchive 3.5.1 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.8 `
  - OK: **bash**: `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)`
  - OK: **sh**: `Ok`
  - OK: **JAVA_HOME**: `openjdk version "11.0.8" 2020-07-14`
  - OK: GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: Fri Aug 26 13:34:52 2022.

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.6 (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.0.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## Parser/Features H L F I J
  - javascript     ‚úì ‚úì ‚úì ‚úì ‚úì
  - typescript     ‚úì ‚úì ‚úì ‚úì ‚úì
  - html           ‚úì ‚úì ‚úì ‚úì ‚úì
  - yaml           ‚úì ‚úì ‚úì ‚úì ‚úì
  - python         ‚úì ‚úì ‚úì ‚úì ‚úì
  - scss           ‚úì . . ‚úì .
  - java           ‚úì ‚úì . ‚úì ‚úì
  - json           ‚úì ‚úì ‚úì ‚úì .
  - tsx            ‚úì ‚úì ‚úì ‚úì ‚úì
  - lua            ‚úì ‚úì ‚úì ‚úì ‚úì
  - go             ‚úì ‚úì ‚úì ‚úì ‚úì

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /Users/fans3210/anaconda3/bin/python3
  - INFO: Python version: 3.9.10
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v18.0.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
      - You may disable this provider (and warning) by adding `let g:loaded_node_provider = 0` to your init.vim

## Perl provider (optional)
  - WARNING: "Neovim::Ext" cpan module is not installed
    - ADVICE:
      - See :help |provider-perl| for more information.
      - You may disable this provider (and warning) by adding `let g:loaded_perl_provider = 0` to your init.vim

renamer: require("renamer.health").check()
========================================================================
## Checking required plugins...
  - OK: "plenary" installed.
  - INFO: Found all required plugins.

## Chechking whether setup was made...

telescope: require("telescope.health").check()
========================================================================
## Checking for required plugins
  - OK: plenary installed.
  - OK: nvim-treesitter installed.

## Checking external dependencies
  - OK: rg: found ripgrep 12.1.1
  - WARNING: fd: not found. Install [sharkdp/fd](https://github.com/sharkdp/fd) for extended capabilities

## ===== Installed extensions =====

## Telescope Extension: `fzf`
  - INFO: No healthcheck provided

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: /Users/fans3210/.cache/nvim/lsp.log
  - WARNING: Log size: 134181 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for go: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for java: ABI version 13
  - OK: Loaded parser for javascript: ABI version 13
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for python: ABI version 13
  - OK: Loaded parser for scss: ABI version 13
  - OK: Loaded parser for tsx: ABI version 13
  - OK: Loaded parser for typescript: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13


```

### Minimal vimrc that can reproduce this bug.

I'm using lua setup, just install everforest, lspsaga and setup a few lsp servers

### Steps to reproduce this bug using minimal vimrc

1. install plugins if everforest, and lspsaga
2. setup lsp servers
3. writting some code with errors
4. using lspsaga "jump diagnostic feature", default key is "]e" 

### Expected behavior

should show diagnostic popup

### Actual behavior

<img width="543" alt="186688830-723258fa-2c91-4bd5-8621-de2749ab5b20" src="https://user-images.githubusercontent.com/6023208/186823592-19124b03-1b67-4260-a4ec-8c24817e9ceb.png">
As we see, the diagnostic shows white color border, it should be red. The border also not smooth.
Tested on "everforest" colorscheme and other schemes from this author also have similar issue eg: gruvbox-material.

Lastest popular colorschemes like tokyonight doesn't have such issue

I've created another issue in lspsaga: https://github.com/glepnir/lspsaga.nvim/issues/459

**Comment by antoineco** [comment]
@fans3210 just so I can frame the root cause, how does this pop-up look outside of tmux?

macOS ships with outdated terminfo files, so some capabilities are disabled inside of tmux, but might be available outside of it.

**Comment by fans3210** [comment]
Hi @antoineco , the popup with or without tmux looks identical.

**Comment by antoineco** [comment]
Ok thanks for checking. I'm looking into it.

**Comment by antoineco** [comment]
@fans3210 the horizontal lines you see on borders are the same markers used for LSP hints. Everforest default styles [use undercurl for these](https://github.com/sainnhe/everforest/blob/04ed8cb87d26b66b5a228c64eb13431d19dea147/colors/everforest.vim#L324-L334), which is more obvious in a terminal that supports this:

<img width="546" alt="lspsaga" src="https://user-images.githubusercontent.com/3299086/186834929-d7a5971e-7e97-4a52-8e0f-193cc6e0ce14.png">
<img width="457" alt="err" src="https://user-images.githubusercontent.com/3299086/186838789-b124141c-90ea-4ba4-897e-58028bfb28f1.png">

I can confirm that this issue doesn't occur with some of the other color schemes I've tried, and the reason is that these color schemes don't use undercurl for `DiagnosticHint`, `DiagnosticWarn`, etc.

---

### Issue breakdown

Lspsaga's [highlight groups](https://github.com/glepnir/lspsaga.nvim/blob/0797b968325ee4dc8dc68e124a8d9a18e6a81888/plugin/lspsaga.lua#L41-L44) link to `DiagnosticHint`, `DiagnosticWarn`, `DiagnosticError`, etc. (as they should), which Everforest links to `HintText`, `WarningText`, `ErrorText`, etc. respectively.

<img width="411" alt="hinttext" src="https://user-images.githubusercontent.com/3299086/186836334-87d7d296-33ac-48c1-96f2-b4d9a58b4bde.png">
<img width="573" alt="hinttext" src="https://user-images.githubusercontent.com/3299086/186838335-e9210328-6a65-4c41-bd5b-26e1c1a2c7b2.png">

Here is the same popup displayed with the [Nord color scheme](https://github.com/shaunsingh/nord.nvim):

<img width="450" alt="norderr" src="https://user-images.githubusercontent.com/3299086/186839638-b62ed0b6-f49d-48ec-8d73-09040c8c0ef0.png">

Aside from the poorly chosen background inside the popup, Nord correctly drops the undercurl for `DiagnosticHint`, `DiagnosticWarn`, `DiagnosticError`, etc.

<img width="495" alt="norddiagerr" src="https://user-images.githubusercontent.com/3299086/186840335-0df9bd59-55fb-42bc-807d-b3474b679b90.png">
<img width="404" alt="nordlspdiagerr" src="https://user-images.githubusercontent.com/3299086/186840472-09246434-c72d-40bc-91a4-73265499a33c.png">

### Possible solution

I'm surprised the same issue doesn't occur with other LSP plugins that display information via popups, but for the time being we could simply re-link [Lspsaga's highlight groups](https://github.com/glepnir/lspsaga.nvim/blob/0797b968325ee4dc8dc68e124a8d9a18e6a81888/plugin/lspsaga.lua#L41-L44) to groups which do not use special styles, such as underline, italics, bold or undercurl.

Quick and dirty demo:

```vim
highlight! link DiagnosticError Red
```

<img width="462" alt="lspred" src="https://user-images.githubusercontent.com/3299086/186845511-2c242b29-8d34-4ddd-995c-d9d6d51290b7.png">

@fans3210 does that look good to you?

**Comment by fans3210** [comment]
Hi @antoineco thanks a lot for the information and possible solution!
